# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") {10} %>

development:
  <<: *default
  database: bleater-dev
  host: db
  username: postgres
  password:

test:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] ||= 'db' %>
  username: <%= ENV['POSTGRES_USER'] ||= 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] ||= '' %>
  database: bleater-test

production:
  <<: *default
  database: bleater
  username: bleater
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>